# Generated by Django 4.2.2 on 2023-06-19 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('year', models.CharField(max_length=10)),
                ('rated', models.CharField(max_length=10)),
                ('released', models.CharField(max_length=20)),
                ('runtime', models.CharField(max_length=20)),
                ('genre', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('writer', models.CharField(max_length=100)),
                ('actors', models.CharField(max_length=100)),
                ('plot', models.CharField(max_length=1000)),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('awards', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=100)),
                ('metascore', models.CharField(max_length=10)),
                ('imdbrating', models.CharField(max_length=10)),
                ('imdbvotes', models.CharField(max_length=20)),
                ('imdbID', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('dvd', models.CharField(max_length=20)),
                ('boxoffice', models.CharField(max_length=20)),
                ('production', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('response', models.CharField(max_length=10)),
            ],
        ),
    ]
