# Generated by Django 4.2.2 on 2023-08-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Year', models.CharField(max_length=10)),
                ('Rated', models.CharField(blank=True, max_length=10)),
                ('Released', models.CharField(blank=True, max_length=20)),
                ('Runtime', models.CharField(blank=True, max_length=20)),
                ('Genre', models.CharField(blank=True, max_length=100)),
                ('Director', models.CharField(blank=True, max_length=100)),
                ('Writer', models.CharField(blank=True, max_length=100)),
                ('Actors', models.CharField(blank=True, max_length=100)),
                ('Plot', models.CharField(blank=True, max_length=1000)),
                ('Language', models.CharField(blank=True, max_length=100)),
                ('Country', models.CharField(blank=True, max_length=100)),
                ('Awards', models.CharField(blank=True, max_length=100)),
                ('Poster', models.CharField(blank=True, max_length=250)),
                ('Ratings', models.JSONField(blank=True)),
                ('Metascore', models.CharField(blank=True, max_length=10)),
                ('imdbRating', models.CharField(blank=True, max_length=10)),
                ('imdbVotes', models.CharField(blank=True, max_length=20)),
                ('imdbID', models.CharField(max_length=20, unique=True)),
                ('Type', models.CharField(blank=True, max_length=20)),
                ('DVD', models.CharField(blank=True, max_length=20)),
                ('BoxOffice', models.CharField(blank=True, max_length=20)),
                ('Production', models.CharField(blank=True, max_length=100)),
                ('Website', models.CharField(blank=True, max_length=100)),
                ('saved', models.BooleanField(default=True)),
                ('dddid', models.CharField(blank=True, max_length=40)),
                ('dddURL', models.CharField(blank=True, max_length=150)),
                ('dddWarnings', models.JSONField(blank=True)),
            ],
        ),
    ]
